import type { jsPDF } from "jspdf";

export const LOW_DPI = 48;
export const HIGH_DPI = 96;
export const DEFAULT_PLATE_WIDTH = 16;
export const PDF_MARGIN_MM = 10;

export const DEFAULT_WATERMARK = {
    title: "Generated by siam-brick.com",
    version: "preview",
};

export function sleep(ms: number) {
    return new Promise((resolve) => setTimeout(resolve, ms));
}

export function setCanvasDpi(canvas: HTMLCanvasElement, dpi: number) {
    canvas.style.width = canvas.style.width || canvas.width + "px";
    canvas.style.height = canvas.style.height || canvas.height + "px";

    const scaleFactor = dpi / 96;
    const width = parseFloat(canvas.style.width);
    const height = parseFloat(canvas.style.height);

    const oldScale = canvas.width / width;
    const backupScale = scaleFactor / oldScale;
    const backup = canvas.cloneNode(false) as HTMLCanvasElement;
    backup.getContext("2d")?.drawImage(canvas, 0, 0);

    const ctx = canvas.getContext("2d");
    if (!ctx) {
        return;
    }

    canvas.width = Math.ceil(width * scaleFactor);
    canvas.height = Math.ceil(height * scaleFactor);

    ctx.setTransform(backupScale, 0, 0, backupScale, 0, 0);
    ctx.drawImage(backup, 0, 0);
    ctx.setTransform(scaleFactor, 0, 0, scaleFactor, 0, 0);
}

export function addWatermark(pdf: jsPDF, isHighQuality: boolean, watermark = DEFAULT_WATERMARK) {
    const pageCount = pdf.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        pdf.setPage(i);
        const pageWidth = pdf.internal.pageSize.getWidth();
        const pageHeight = pdf.internal.pageSize.getHeight();
        const baseFont = Math.max(6, Math.min(pageWidth, pageHeight) * 0.018);
        const fontSize = isHighQuality ? baseFont * 1.1 : baseFont;
        pdf.setFontSize(fontSize);
        pdf.setTextColor(180);
        const margin = Math.max(5, Math.min(pageWidth, pageHeight) * 0.04);
        const x = pageWidth - margin;
        const y = margin;
        pdf.text(watermark.title, x, y, { align: "right" });
        pdf.text(watermark.version, x, y + fontSize * 0.85, { align: "right" });
    }
}
