import type { jsPDF } from "jspdf";

export const LOW_DPI = 48;
export const HIGH_DPI = 96;
export const DEFAULT_PLATE_WIDTH = 16;

export const DEFAULT_WATERMARK = {
    title: "Generated by siam-brick.com",
    version: "preview",
};

export function sleep(ms: number) {
    return new Promise((resolve) => setTimeout(resolve, ms));
}

export function setCanvasDpi(canvas: HTMLCanvasElement, dpi: number) {
    canvas.style.width = canvas.style.width || canvas.width + "px";
    canvas.style.height = canvas.style.height || canvas.height + "px";

    const scaleFactor = dpi / 96;
    const width = parseFloat(canvas.style.width);
    const height = parseFloat(canvas.style.height);

    const oldScale = canvas.width / width;
    const backupScale = scaleFactor / oldScale;
    const backup = canvas.cloneNode(false) as HTMLCanvasElement;
    backup.getContext("2d")?.drawImage(canvas, 0, 0);

    const ctx = canvas.getContext("2d");
    if (!ctx) {
        return;
    }

    canvas.width = Math.ceil(width * scaleFactor);
    canvas.height = Math.ceil(height * scaleFactor);

    ctx.setTransform(backupScale, 0, 0, backupScale, 0, 0);
    ctx.drawImage(backup, 0, 0);
    ctx.setTransform(scaleFactor, 0, 0, scaleFactor, 0, 0);
}

export function addWatermark(pdf: jsPDF, isHighQuality: boolean, watermark = DEFAULT_WATERMARK) {
    const pageCount = pdf.internal.getNumberOfPages();
    const fontSize = isHighQuality ? 20 : 10;
    for (let i = 1; i <= pageCount; i++) {
        pdf.setPage(i);
        pdf.setFontSize(fontSize);
        pdf.setTextColor(180);
        pdf.text(
            watermark.title,
            pdf.internal.pageSize.getWidth() * 0.25,
            pdf.internal.pageSize.getHeight() * 0.3
        );
        pdf.text(
            watermark.version,
            pdf.internal.pageSize.getWidth() * 0.25,
            pdf.internal.pageSize.getHeight() * 0.3 + 10
        );
    }
}
